name: Sync Private Repo to Public Repo

on:
  push:
    branches:
      - main  # Change if you use a different branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures we get full commit history

      - name: Push to Public Repo
        run: |
          git config --global user.email "shivarajmbb43@gmail.com"
          git config --global user.name "ShivarajMBB"
          git remote add public https://x-access-token:${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}@github.com/ShivarajMBB/Streamlit-repo.git
          git push --force public main
